# -*- coding: utf-8 -*-

# This is a part of "ČHMÚ - Data o počasí," a QGIS plugin that processes meteorological data published by CHMI.  
# Copyright (C) 2025 by Mikuláš Kadečka - mikulas.kad@seznam.cz  

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
# This script initializes the plugin, making it known to QGIS.
# Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/



# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DataCHMU class from file DataCHMU.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .data_chmu import DataCHMU
    return DataCHMU(iface)
